### ISSUE TITLE
Error at android\app\src\main\java\org\tensorflow\lite\examples\detection\CameraActivity.java:53: 

### ISSUE THREAD

**Issue by lavsharmaa** [codePerfectPlus/American_sign_Language_detection#1]
- After doing the gradle sync and when running the project getting the following error
**android\app\src\main\java\org\tensorflow\lite\examples\detection\CameraActivity.java:53: error: package org.tensorflow.lite.examples.detection.env does not exist
import org.tensorflow.lite.examples.detection.env.ImageUtils;**

**Comment by codeperfectplus** [comment]
It's working fine on My pc. @lavsharmaa 
I am mainly in Python and Deep learning So I have a limited understanding of Android. This Repo main purpose is to convert the Tensorflow model to TFLite and Deploy it to android.SO I will not able to help in android.

**Comment by lavsharmaa** [comment]
Alright. If I find anything I will update in this issue and then maybe you can crosscheck and verify it further.

**Comment by lavsharmaa** [comment]
So, the issue is at ```android/app/src/main/java/org/tensorflow/lite/examples/detection/``` you forgot to push the ```env``` folder due to which the error is coming. Just check once. I have added the ```env``` folder externally and the error is solved.

**Comment by lavsharmaa** [comment]
So, the issue is at ```android/app/src/main/java/org/tensorflow/lite/examples/detection/``` you forgot to push the ```env``` folder due to which the error is coming. Just check once. I have added the ```env``` folder externally and the error is solved.

**Comment by codeperfectplus** [comment]
Maybe it was due to the .gitignore.

**Comment by lavsharmaa** [comment]
Yes as ```env``` is included in the ```.gitignore```. Just update that in the repo so that no one else faces that issue.

**Comment by codeperfectplus** [comment]
Thanks, @lavsharmaa for improving the repo.
